/// Generated by AssetsRefGenerator on 2021/06/04
class Res {
  static const String about_us = "assets/icons/about_us.svg";
  static const String back = "assets/icons/back.svg";
  static const String cart = "assets/icons/cart.svg";
  static const String category = "assets/icons/category.svg";
  static const String chat = "assets/icons/chat.svg";
  static const String heart = "assets/icons/heart.svg";
  static const String home = "assets/icons/home.svg";
  static const String login = "assets/icons/login.svg";
  static const String order = "assets/icons/order.svg";
  static const String search = "assets/icons/search.svg";
  static const String trash_can = "assets/icons/trash-can.svg";
  static const String view = "assets/icons/view.svg";
  static const String fan = "assets/images/fan.png";
  static const String main_top = "assets/images/main_top.png";
}
